// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeansPlayground.Core.Data;

#nullable disable

namespace SeansPlayground.Core.Migrations
{
    [DbContext(typeof(PlaygroundDbContext))]
    [Migration("20260610205551_AddBackgroundAndPlaygroundModel")]
    partial class AddBackgroundAndPlaygroundModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PlainText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plain_text");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_file_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Title")
                        .IsUnique();

                    b.ToTable("documents", "background");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundDocumentSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("heading");

                    b.Property<int>("SectionOrder")
                        .HasColumnType("integer")
                        .HasColumnName("section_order");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "Heading")
                        .IsUnique();

                    b.ToTable("document_sections", "background");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundEducationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DegreeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("degree_name");

                    b.Property<string>("FieldOfStudy")
                        .HasColumnType("text")
                        .HasColumnName("field_of_study");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("institution_name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "DegreeName", "InstitutionName")
                        .IsUnique();

                    b.ToTable("education_items", "background");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundExperience", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DateLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("date_label");

                    b.Property<string>("DurationLabel")
                        .HasColumnType("text")
                        .HasColumnName("duration_label");

                    b.Property<DateOnly?>("EndOn")
                        .HasColumnType("date")
                        .HasColumnName("end_on");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_name");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_title");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateOnly>("StartOn")
                        .HasColumnType("date")
                        .HasColumnName("start_on");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "OrganizationName", "RoleTitle", "StartOn")
                        .IsUnique();

                    b.ToTable("experiences", "background");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundExperienceHighlight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExperienceId")
                        .HasColumnType("bigint")
                        .HasColumnName("experience_id");

                    b.Property<string>("HighlightText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("highlight_text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId", "SortOrder")
                        .IsUnique();

                    b.ToTable("experience_highlights", "background");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("biography");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headline");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("profiles", "background");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundRepository", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("OwnerName", "RepositoryName")
                        .IsUnique();

                    b.ToTable("repositories", "background");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundSectionEntitlement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section_key");

                    b.HasKey("Id");

                    b.HasIndex("SectionKey", "RoleName")
                        .IsUnique();

                    b.ToTable("section_entitlements", "background");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundSocialLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<long>("PlatformId")
                        .HasColumnType("bigint")
                        .HasColumnName("platform_id");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.HasIndex("ProfileId", "PlatformId", "Url")
                        .IsUnique();

                    b.ToTable("social_links", "background");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundSocialPlatform", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("social_platforms", "background");
                });

            modelBuilder.Entity("SeansPlayground.Core.Nasa.NasaApodImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("ApodDate")
                        .HasColumnType("date")
                        .HasColumnName("apod_date");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("Copyright")
                        .HasColumnType("text")
                        .HasColumnName("copyright");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("HdUrl")
                        .HasColumnType("text")
                        .HasColumnName("hd_url");

                    b.Property<byte[]>("ImageBytes")
                        .HasColumnType("bytea")
                        .HasColumnName("image_bytes");

                    b.Property<string>("JsonPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json_payload");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ApodDate")
                        .IsUnique();

                    b.ToTable("apod_images", "nasa");
                });

            modelBuilder.Entity("SeansPlayground.Core.Nasa.NasaDonkiEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("event_type");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("JsonPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json_payload");

                    b.Property<DateTimeOffset?>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "EventDate");

                    b.HasIndex("EventType", "ExternalId")
                        .IsUnique();

                    b.ToTable("donki_events", "nasa");
                });

            modelBuilder.Entity("SeansPlayground.Core.Playground.PlaygroundEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.HasKey("Id");

                    b.ToTable("playground_events", "public");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundDocument", b =>
                {
                    b.HasOne("SeansPlayground.Core.Background.BackgroundProfile", "Profile")
                        .WithMany("Documents")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundDocumentSection", b =>
                {
                    b.HasOne("SeansPlayground.Core.Background.BackgroundDocument", "Document")
                        .WithMany("Sections")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundEducationItem", b =>
                {
                    b.HasOne("SeansPlayground.Core.Background.BackgroundProfile", "Profile")
                        .WithMany("EducationItems")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundExperience", b =>
                {
                    b.HasOne("SeansPlayground.Core.Background.BackgroundProfile", "Profile")
                        .WithMany("Experiences")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundExperienceHighlight", b =>
                {
                    b.HasOne("SeansPlayground.Core.Background.BackgroundExperience", "Experience")
                        .WithMany("Highlights")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundRepository", b =>
                {
                    b.HasOne("SeansPlayground.Core.Background.BackgroundProfile", "Profile")
                        .WithMany("Repositories")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundSocialLink", b =>
                {
                    b.HasOne("SeansPlayground.Core.Background.BackgroundSocialPlatform", "Platform")
                        .WithMany("Links")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeansPlayground.Core.Background.BackgroundProfile", "Profile")
                        .WithMany("SocialLinks")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundDocument", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundExperience", b =>
                {
                    b.Navigation("Highlights");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundProfile", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("EducationItems");

                    b.Navigation("Experiences");

                    b.Navigation("Repositories");

                    b.Navigation("SocialLinks");
                });

            modelBuilder.Entity("SeansPlayground.Core.Background.BackgroundSocialPlatform", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
